# Generated by Django 5.0.6 on 2024-07-03 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='category_name')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/categories/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='sub_category_name')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/sub_categories/', verbose_name='image')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='shop.category')),
            ],
            options={
                'verbose_name': 'sub_category',
                'verbose_name_plural': 'sub_categories',
            },
        ),
    ]
