# Generated by Django 5.0.6 on 2024-07-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_middle',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/', verbose_name='image_middle'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/', verbose_name='image_small'),
        ),
    ]
