# Generated by Django 5.0.6 on 2024-07-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_image_middle_product_image_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/<django.db.models.fields.CharField>', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_middle',
            field=models.ImageField(blank=True, null=True, upload_to='products/<django.db.models.fields.CharField>', verbose_name='image_middle'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='products/<django.db.models.fields.CharField>', verbose_name='image_small'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_categories/', verbose_name='image'),
        ),
    ]
