# Generated by Django 5.0.6 on 2024-07-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/norm/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_middle',
            field=models.ImageField(blank=True, null=True, upload_to='products/middle/', verbose_name='image_middle'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='products/small/', verbose_name='image_small'),
        ),
    ]
